More protections

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -6,7 +6,33 @@ on:
       - 'v[0-9]+.[0-9]+.[0-9]+'
 
 jobs:
+  prechecks:
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4.1.1
+
+      - name: Verify Tag Format
+        id: verify_tag
+        run: |
+          if [[ ! "${GITHUB_REF}" =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+            echo "Tag ${GITHUB_REF} does not match required format vX.Y.Z"
+            exit 1
+          fi
+      
+      - name: Check main branch
+        id: check_branch
+        run: |
+          git fech origin main
+
+          if ! git merge-base --is-ancestor ${GITHUB_SHA} origin/main; then
+            echo "Tag ${GITHUB_REF} is not based on the latest main branch"
+            exit 1
+          fi
+
   deploy-python:
+    needs: prechecks
     runs-on: ubuntu-latest
 
     steps:
